server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma User"
appVersion: "1.0.0"
