server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
appDescription: "Pragma Plazoleta"
appVersion: "1.0.0"

# JWT Configuration
jwt:
  secret: ff739b6a3d0427aaa511ba0d5e991df7b92a91589bc59db823c6db6fd0a93c6c

external-apis:
  user:
    get-user:
      url: "http://localhost:8081/api/v1/user"